INSERT INTO DIRECTORY_VIEWS (ID, NAME, COLLECTION, LAYOUT, FIELD, TYPE) VALUES (1, 'People', 'persons', 'LIST', 'name', 'STARTING_WITH');
INSERT INTO DIRECTORY_VIEW_FACETS (DIRECTORY_VIEW_ID, NAME, FIELD, DEFAULT_LIMIT, DEFAULT_SORT) VALUES (1, 'Type', 'type', 10, 'COUNT');


INSERT INTO DIRECTORY_VIEWS (ID, NAME, COLLECTION, LAYOUT, FIELD, TYPE) VALUES (2, 'Organizations', 'organizations', 'LIST', 'name', 'STARTING_WITH');
INSERT INTO DIRECTORY_VIEW_FACETS (DIRECTORY_VIEW_ID, NAME, FIELD, DEFAULT_LIMIT, DEFAULT_SORT) VALUES (2, 'Type', 'type', 10, 'COUNT');


INSERT INTO DIRECTORY_VIEWS (ID, NAME, COLLECTION, LAYOUT, FIELD, TYPE) VALUES (3, 'Research', 'documents', 'LIST', 'title', 'STARTING_WITH');
INSERT INTO DIRECTORY_VIEW_FACETS (DIRECTORY_VIEW_ID, NAME, FIELD, DEFAULT_LIMIT, DEFAULT_SORT) VALUES (3, 'Type', 'type', 10, 'COUNT');
