PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?feature rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> vivo:features ?feature .
    ?feature rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?feature), "(^.*/)", "::") ) AS ?labelWithId ) .
}