PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?translator vitro:mostSpecificType ?mostSpecificTypeWithId .
} WHERE {
    <[(${uri})]> bibo:translator ?translator .
    ?translator vitro:mostSpecificType ?mostSpecificType .
    BIND( CONCAT( STR(?mostSpecificType), REPLACE(STR(?translator), "(^.*/)", "::") ) AS ?mostSpecificTypeWithId ) .
}