env:
  global:
    - COVERALLS_PARALLEL=true
    - COVERALLS_SERVICE_NAME=travis-ci
    - COVERALLS_SERVICE_NUMBER=$TRAVIS_BUILD_NUMBER
    - COVERALLS_SERVICE_JOB_ID=$TRAVIS_JOB_ID

matrix:
  include:
  - name: "Middleware Tests"
    language: java
    jdk: oraclejdk8
    before_script:
      - cd middleware
    script:
      - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn clean test cobertura:cobertura jacoco:report
    after_success:
      - mvn coveralls:report -DserviceName=$COVERALLS_SERVICE_NAME -DserviceBuildNumber=$COVERALLS_SERVICE_NUMBER

  - name: "UI Tests"
    language: node_js
    node_js: "8"
    addons:
      chrome: stable
    before_install:
      - cd ui
    install:
      - yarn install
    before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sleep 3 # give xvfb some time to start
    script:
      - yarn test:ci
    after_success:
      - yarn test:report

# Deploy Github pages after success of Middleware Tests.
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: false
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  local_dir: "./middleware/target/generated-docs"
  on:
    branch: master
    condition: $TRAVIS_JOB_NAME = "Middleware Tests"

# Send final notification to coveralls after all jobs have been completed.
notifications:
  webhooks:
    urls:
      - https://coveralls.io/webhook