PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?assignedBy rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> vivo:assignedBy ?assignedBy ; a vivo:Grant .
    ?assignedBy rdfs:label ?label ; a foaf:Organization .
    BIND( CONCAT( STR(?label), REPLACE(STR(?assignedBy), "(^.*/)", "::") ) AS ?labelWithId ) .
}