PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?assignedBy vitro:mostSpecificType ?mostSpecificTypeWithId .
} WHERE {
    <[(${uri})]> vivo:assignedBy ?assignedBy ; a vivo:Grant .
    ?assignedBy vitro:mostSpecificType ?mostSpecificType ; a foaf:Organization .
    BIND( CONCAT( STR(?mostSpecificType), REPLACE(STR(?assignedBy), "(^.*/)", "::") ) AS ?mostSpecificTypeWithId ) .
}
