PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?dateTimeEnd vivo:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> vivo:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval vivo:end ?dateTimeEnd .
    ?dateTimeEnd vivo:dateTime ?dateTime .
}
