PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?grantSubcontractedThrough rdfs:label ?label .
} WHERE {
    <[(${uri})]> vivo:grantSubcontractedThrough ?grantSubcontractedThrough .
    ?grantSubcontractedThrough rdfs:label ?label .
}