PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?inheresInType vitro:mostSpecificType ?mostSpecificType .
} WHERE {
    <[(${uri})]> obo:RO_0000052 ?inheresInType .
    ?inheresInType vitro:mostSpecificType ?mostSpecificType .
}
