PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?inheresIn rdfs:label ?label .
} WHERE {
    <[(${uri})]> obo:RO_0000052 ?inheresIn .
    ?inheresIn rdfs:label ?label .
}
