PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?outputOf rdfs:label ?label .
} WHERE {
    <[(${uri})]> obo:OBI_0000312 ?outputOf .
    ?outputOf rdfs:label ?label .
}
