CONSTRUCT {
    ?relationship ?property ?value .
} WHERE {
    #?relationship a <[(${uri})]> .
    ?relationship a <http://vivoweb.org/ontology/core#AwardReceipt> .
    ?relationship ?property ?value .
}
