PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?subGrantOf rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> obo:BFO_0000050 ?subGrantOf ; a vivo:Grant .
    ?subGrantOf rdfs:label ?label ; a vivo:Grant .
    BIND( CONCAT( STR(?label), REPLACE(STR(?subGrantOf), "(^.*/)", "::") ) AS ?labelWithId ) .
}