PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?dateTimeValue vivo:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> vivo:dateTimeValue ?dateTimeValue ; a vivo:AwardReceipt .
    ?dateTimeValue vivo:dateTime ?dateTime .
}
