PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    <[(${uri})]> vivo:contactInformation ?contactInformation .
} WHERE {
    <[(${uri})]> vivo:contactInformation ?contactInformation .
}
