PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?output rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> obo:RO_0002234 ?output .
    ?output rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?output), "(^.*/)", "::") ) AS ?labelWithId ) .
}