PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?subject rdfs:label ?label .
} WHERE {
    <[(${uri})]> vivo:hasSubjectArea ?subject .
    ?subject rdfs:label ?label .
}