PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?facility rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> obo:RO_0001025  ?facility .
    ?facility a vivo:Facility .
    ?facility rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?facility), "(^.*/)", "::") ) AS ?labelWithId ) .
}