PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX event: <http://purl.org/NET/c4dm/event.owl#>

CONSTRUCT {
    ?process rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> obo:BFO_0000050 ?process .
    ?process a event:Event .
    ?process rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?process), "(^.*/)", "::") ) AS ?labelWithId ) .
}
