PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?offeredBy vitro:mostSpecificType ?type .
} WHERE {
    <[(${uri})]> vivo:offeredBy ?offeredBy .
    ?offeredBy vitro:mostSpecificType ?type .
    FILTER(?type != foaf:Organization)
}
