PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?work vitro:mostSpecificType ?mostSpecificTypeWithId .
} WHERE {
    <[(${uri})]> obo:RO_0002234 ?work .
    ?work vitro:mostSpecificType ?mostSpecificType .
    BIND( CONCAT( STR(?mostSpecificType), REPLACE(STR(?work), "(^.*/)", "::") ) AS ?mostSpecificTypeWithId ) .
    FILTER (?mostSpecificType != vivo:DateTimeValue)
}