PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?work rdfs:label ?name .
} WHERE {
    <[(${uri})]> obo:RO_0002234 ?work .
    ?work rdfs:label ?name .
}