PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?person rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> obo:BFO_0000055 ?person .
    ?person a foaf:Person .
    ?person rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?person), "(^.*/)", "::") ) AS ?labelWithId ) .
}