PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?course rdfs:label ?name .
} WHERE {
    <[(${uri})]> vivo:prerequisiteFor ?course .
    ?course rdfs:label ?name .
}