PREFIX bibo:  <http://purl.org/ontology/bibo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?document vitro:mostSpecificType ?type .
} WHERE {
    <[(${uri})]> bibo:presents ?document .
    ?document vitro:mostSpecificType ?type .
    FILTER (?type != vivo:DateTimeValue)
}