PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?relatedBy vivo:rank ?rank .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?relatedBy .
    ?relatedBy a vivo:Authorship .
    ?relatedBy vivo:relates ?author .
    ?relatedBy vivo:rank ?rank .

    FILTER (?author != <[(${uri})]>) .
}