PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?author vitro:mostSpecificType ?mostSpecificType .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?relatedBy .
    ?relatedBy a vivo:Authorship .
    ?relatedBy vivo:relates ?author .
    ?author a foaf:Person .
    ?author vitro:mostSpecificType ?mostSpecificType .
}