PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?citedBy rdfs:label ?label .
} WHERE {
    <[(${uri})]> bibo:citedBy ?citedBy .
    ?citedBy rdfs:label ?label .
}
