PREFIX cito: <http://purl.org/spar/cito/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?dataSource vitro:mostSpecificType ?mostSpecificTypeWithId .
} WHERE {
    <[(${uri})]> cito:citesAsDataSource ?citesAsDataSource .
    ?citesAsDataSource vitro:mostSpecificType ?mostSpecificType .
    BIND( CONCAT( STR(?mostSpecificType), REPLACE(STR(?citesAsDataSource), "(^.*/)", "::") ) AS ?mostSpecificTypeWithId ) .
}