PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?dateTimeStart vivo:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> vivo:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval vivo:start ?dateTimeStart .
    ?dateTimeStart vivo:dateTime ?dateTime .
}
