PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?documentPart rdfs:label ?label .
} WHERE {
    <[(${uri})]> obo:BFO_0000051 ?documentPart .
    ?documentPart vitro:mostSpecificType ?mostSpecificType .
    ?documentPart rdfs:label ?label .

    FILTER (?mostSpecificType != vivo:DateTimeValue) .
}
