PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX scholars: <http://scholars.library.tamu.edu/vivo/individual/>

CONSTRUCT {
    <[(${uri})]> ?property ?object .
} WHERE {
    <[(${uri})]> ?property ?object .
    FILTER (?property != core:dateTimeValue)
    FILTER (?property != core:hasPublicationVenue)
    FILTER (?property != rdf:type)
    FILTER (?object != core:DateTimeValue)
}
