PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?documentPart rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> obo:BFO_0000051 ?documentPart .
    ?documentPart rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?documentPart), "(^.*/)", "::") ) AS ?labelWithId ) .
}