PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?relatedBy vivo:rank ?rank .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?relatedBy .
    ?relatedBy a vivo:Editorship .
    ?relatedBy vivo:relates ?editor .
    ?editor a foaf:Person .
    ?relatedBy vivo:rank ?rank .
}