PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?chair rdfs:label ?label .
} WHERE {
    <[(${uri})]> tamu:ETDChairedBy ?chair .
    ?chair rdfs:label ?label .
}
