PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?geographicFocus vitro:mostSpecificType ?mostSpecificType .
} WHERE {
    <[(${uri})]> vivo:geographicFocus ?geographicFocus .
    ?geographicFocus vitro:mostSpecificType ?mostSpecificType .
    
#    FILTER (STRSTARTS (str(?mostSpecificType), str(vivo:))) .
}