PREFIX c4o: <http://purl.org/spar/c4o/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?globalCitationFrequency rdfs:label ?label .
} WHERE {
    <[(${uri})]> c4o:hasGlobalCitationFrequency ?globalCitationFrequency .
    ?globalCitationFrequency rdfs:label ?label .
}