PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>

CONSTRUCT {
    ?image vitro-public:mimeType ?mimeType .
} WHERE {
    <[(${uri})]> vitro-public:mainImage ?image .
    ?image vitro-public:mimeType ?mimeType .
}
