PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?isAbout vitro:mostSpecificType ?mostSpecificType .
} WHERE {
    <[(${uri})]> obo:IAO_0000136 ?isAbout .
    ?isAbout vitro:mostSpecificType ?mostSpecificType .

    FILTER (?mostSpecificType != vivo:DateTimeValue) .
}
