PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?mention vitro:mostSpecificType ?typeWithId .
} WHERE {
    <[(${uri})]> obo:IAO_0000142 ?mention .
    ?mention vitro:mostSpecificType ?type .
	BIND( CONCAT( STR(?type), REPLACE(STR(?mention), "(^.*/)", "::") ) AS ?typeWithId ) .
    FILTER (?type != vivo:DateTimeValue) .
}