PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?presentedAt rdfs:label ?label .
} WHERE {
    <[(${uri})]> bibo:presentedAt ?presentedAt .
    ?presentedAt rdfs:label ?label .
}
