PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?presentedAt vitro:mostSpecificType ?mostSpecificTypeWithId .
} WHERE {
    <[(${uri})]> bibo:presentedAt ?presentedAt .
    ?presentedAt vitro:mostSpecificType ?mostSpecificType .
    BIND( CONCAT( STR(?mostSpecificType), REPLACE(STR(?presentedAt), "(^.*/)", "::") ) AS ?mostSpecificTypeWithId ) .
}