PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX bibo: <http://purl.org/ontology/bibo/>

CONSTRUCT {
    ?publicationVenue bibo:issn ?issn .
} WHERE {
    <[(${uri})]> vivo:hasPublicationVenue ?publicationVenue .
    ?publicationVenue bibo:issn ?issn .
}
