PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?publisher rdfs:label ?label .
} WHERE {
    <[(${uri})]> vivo:publisher ?publisher .
    ?publisher rdfs:label ?label .
}
