PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?publicationDate vivo:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> vivo:dateTimeValue ?publicationDate .
    ?publicationDate vivo:dateTime ?dateTime .
}
