PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX bibo: <http://purl.org/ontology/bibo/>

CONSTRUCT {
    ?publicationVenueFor bibo:issn ?issn .
} WHERE {
    <[(${uri})]> vivo:hasPublicationVenueFor ?publicationVenueFor .
    ?publicationVenueFor bibo:issn ?issn .
}