PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?publisher rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> vivo:publisher ?publisher .
    ?publisher rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?publisher), "(^.*/)", "::") ) AS ?labelWithId ) .
}