PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?publicationVenue rdfs:label ?label .
} WHERE {
    <[(${uri})]> vivo:hasPublicationVenueFor ?publicationVenue .
    ?publicationVenue rdfs:label ?label .
}