PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?publisher rdfs:label ?nameWithId .
} WHERE {
    <[(${uri})]> vivo:publisher ?publisher .
    ?publisher rdfs:label ?name .
    BIND( CONCAT( STR(?name), REPLACE(STR(?publisher), "(^.*/)", "::") ) AS ?nameWithId ) .
}