PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?publicationDate vivo:dateTimePrecision ?dateTimePrecision .
} WHERE {
    <[(${uri})]> vivo:dateTimeValue ?publicationDate .
    ?publicationDate vivo:dateTimePrecision ?dateTimePrecision .
}
