PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?reproducedIn rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> bibo:reproducedIn ?reproducedIn .
    ?reproducedIn rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?reproducedIn), "(^.*/)", "::") ) AS ?labelWithId ) .
}