PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?subjectArea rdfs:label ?label .
} WHERE {
    <[(${uri})]> vivo:hasSubjectArea ?subjectArea .
    ?subjectArea rdfs:label ?label .
}
