PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?informationResource vitro:mostSpecificType ?mostSpecificType .
} WHERE {
    <[(${uri})]> vivo:informationResourceSupportedBy ?informationResource .
    ?informationResource vitro:mostSpecificType ?mostSpecificType .

    FILTER (?mostSpecificType != vivo:DateTimeValue) .
}