PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?informationResource vitro:mostSpecificType ?typeWithId .
} WHERE {
    <[(${uri})]> vivo:informationResourceSupportedBy ?informationResource .
    ?informationResource vitro:mostSpecificType ?type .
    BIND( CONCAT( STR(?type), REPLACE(STR(?informationResource), "(^.*/)", "::") ) AS ?typeWithId ) .
    FILTER (?type != vivo:DateTimeValue) .
}