PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?informationResource vitro:mostSpecificType ?mostSpecificTypeWithId .
} WHERE {
    <[(${uri})]> vivo:informationResourceSupportedBy ?informationResource .
    ?informationResource vitro:mostSpecificType ?mostSpecificType .
    BIND( CONCAT( STR(?mostSpecificType), REPLACE(STR(?informationResource), "(^.*/)", "::") ) AS ?mostSpecificTypeWithId ) .
    FILTER (?mostSpecificType != vivo:DateTimeValue) .
}