PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?translator rdfs:label ?nameWithId .
} WHERE {
    <[(${uri})]> bibo:translator ?translator .
    ?translator rdfs:label ?name .
    BIND( CONCAT( STR(?name), REPLACE(STR(?translator), "(^.*/)", "::") ) AS ?nameWithId ) .
}