PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?translationOf rdfs:label ?label .
} WHERE {
    <[(${uri})]> vivo:hasTranslation ?translationOf .
    ?translationOf rdfs:label ?label .
    ?translationOf vitro:mostSpecificType ?mostSpecificType .

    FILTER (?mostSpecificType != vivo:DateTimeValue) .
}
