PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    <[(${uri})]> vitro:mostSpecificType ?mostSpecificType .
} WHERE {
    <[(${uri})]> vitro:mostSpecificType ?mostSpecificType .
    FILTER (?mostSpecificType != vivo:DateTimeValue)
}