PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
    ?author rdfs:label ?label .
    ?author vcard:email ?email .
    ?author core:hrJobTitle ?hrJobTitle .
    ?author core:orcidId ?orcidId .
} WHERE {
    <[(${uri})]> core:relatedBy ?authorship .
    ?authorship a core:Authorship .
    ?authorship core:relates ?author .
    ?author a foaf:Person .
    ?author rdfs:label ?label .
    ?author vcard:email ?email .
    ?author core:hrJobTitle ?hrJobTitle .
    OPTIONAL { ?author core:orcidId ?orcidId . }
}