PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?author rdfs:label ?name .
} WHERE {
    <[(${uri})]> core:relatedBy ?authorship .
    ?authorship a core:Authorship .
    ?authorship core:relates ?author .
    ?author a foaf:Person .
    ?author rdfs:label ?name .
}
