PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?journal rdfs:label ?title .
    ?journal bibo:issn ?issn .
} WHERE {
    <[(${uri})]>  bibo:* ?publication .
    ?publication core:hasPublicationVenue ?journal .
    ?journal rdfs:label ?title .
    ?journal bibo:issn ?issn .
}

