PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?publisher rdfs:label ?name .
} WHERE {
    <[(${uri})]> bibo:* ?publication .
    ?publication core:hasPublicationVenue ?publicationVenue .
    ?publicationVenue core:publisher ?publisher . 
    ?publisher rdfs:label ?name .
}
