PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?publication ?property ?object .
} WHERE {
    <[(${uri})]> bibo:* ?publication .
    ?publication ?property ?object .
    FILTER (?property != core:dateTimeValue)
    FILTER (?property != core:hasPublicationVenue)
    FILTER (?property != rdf:type)
}
