PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?broader rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> skos:broader ?broader .
    ?broader rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?broader), "(^.*/)", "::") ) AS ?labelWithId ) .
}