PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?researchAreaOf rdfs:label ?label .
} WHERE {
    <[(${uri})]> vivo:researchAreaOf ?researchAreaOf .
    ?researchAreaOf rdfs:label ?label .
    FILTER (lang(?name) = '')
}