PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?grant vivo:dateTime ?dateTimeWithId .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?role .
    ?role a vivo:AdministratorRole .
    ?role vivo:relatedBy ?grant .
    ?grant a vivo:Grant .
    ?grant vivo:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval vivo:start ?date .
    ?date vivo:dateTime ?dateTime .
    BIND( CONCAT( STR(?dateTime), REPLACE(STR(?grant), "(^.*/)", "::") ) AS ?dateTimeWithId ) .
}