PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?patent vivo:dateTime ?dateTimeWithId .
} WHERE {
    <[(${uri})]> vivo:assigneeFor ?patent .
    ?patent vivo:dateTimeValue ?date .
    ?date vivo:dateTime ?dateTime .
    BIND( CONCAT( STR(?dateTime), REPLACE(STR(?patent), "(^.*/)", "::") ) AS ?dateTimeWithId ) .
}