PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?award vivo:dateTimeValue ?date .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?award .
    ?award a vivo:Award .
    ?award vivo:dateTimeValue ?date .
    ?date vivo:dateTime ?dateTime .
}