PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?grant vivo:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> vivo:assigns ?grant .
    ?grant a vivo:Grant .
    ?grant vivo:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval vivo:start ?date .
    ?date vivo:dateTime ?dateTime .
}