PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
    ?vcard vcard:geo ?geo .
} WHERE {
    <[(${uri})]> obo:ARG_2000028 ?vcard .
    ?vcard vcard:geo ?geo .
}