PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?organization rdfs:label ?name .
} WHERE {
    <[(${uri})]> vivo:affiliatedOrganization ?organization .
    ?organization rdfs:label ?name .
    FILTER (lang(?name) = '')
}