PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?equipment rdfs:label ?name .
} WHERE {
    <[(${uri})]> vivo:hasEquipment ?equipment .
    ?equipment rdfs:label ?name .
}