PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?degree rdfs:label ?name .
} WHERE {
    <[(${uri})]> core:offers ?degree .
    ?degree a core:AcademicDegree .
    ?degree rdfs:label ?name .
}
