PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?degree rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> vivo:offers ?degree .
    ?degree a vivo:AcademicDegree .
    ?degree rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?degree), "(^.*/)", "::") ) AS ?labelWithId ) .
}