PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?organization a <[(${uri})]> .
    ?organization rdfs:label ?name .
    ?organization vitro:mostSpecificType ?type .
} WHERE {
    ?organization a <[(${uri})]> .
    ?organization rdfs:label ?name .
    ?organization vitro:mostSpecificType ?type .
}