PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?person rdfs:label ?name .
    ?person core:hrJobTitle ?title .
    ?person vitro:mostSpecificType ?type .
} WHERE {
    <[(${uri})]> core:relatedBy ?position .
    ?position a core:Position .
    ?position core:relatedBy ?person .
    ?person a foaf:Person .
    ?person rdfs:label ?name .
    ?person core:hrJobTitle ?title .
    ?person vitro:mostSpecificType ?type .
    FILTER (lang(?name) = '')
}
