PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?person core:hrJobTitle ?title .
} WHERE {
    <[(${uri})]> core:relatedBy ?position .
    ?position a core:Position .
    ?position core:relatedBy ?person .
    ?person a foaf:Person .
    ?person core:hrJobTitle ?title .
}
