PREFIX vivo: <http://vivoweb.org/ontology/vivo#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?person vivo:hrJobTitle ?title .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?position .
    ?position a vivo:Position .
    ?position vivo:relatedBy ?person .
    ?person a foaf:Person .
    ?person vivo:hrJobTitle ?title .
}