PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?publication vitro:mostSpecificType ?type .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?authorship .
    ?authorship a vivo:Authorship .
    ?authorship vivo:relates ?publication .
    ?publication a obo:IAO_0000030 .
    ?publication vitro:mostSpecificType ?type .
}