PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?award vivo:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> vivo:sponsors ?award .
    ?award a vivo:Award .
    ?award vivo:dateTimeValue ?date .
    ?date vivo:dateTime ?dateTime .
}