PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

CONSTRUCT {
    ?publication vivo:dateTime ?dateTimeWithId .
} WHERE {
    <[(${uri})]> vivo:translatorOf ?publication .
    ?publication a obo:IAO_0000030 .
    ?publication vivo:dateTimeValue ?date .
    ?date vivo:dateTime ?dateTime .
    BIND( CONCAT( STR(?dateTime), REPLACE(STR(?publication), "(^.*/)", "::") ) AS ?dateTimeWithId ) .
}