PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?advising rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?role .
    ?role a vivo:AdvisorRole .
    ?role vivo:relatedBy ?advising .
    ?advising a vivo:AdvisingRelationship .
    ?advising rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?advising), "(^.*/)", "::") ) AS ?labelWithId ) .
}