PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?advisee rdfs:label ?label .
    ?advisee core:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> core:relatedBy ?advisingRelationship .
    ?advisingRelationship a core:AdvisingRelationship .
    ?advisingRelationship core:relates ?advisee .
    ?advisee a foaf:Person .
    ?advisee obo:RO_0000053 ?adviseeRole .
    ?adviseeRole a core:AdviseeRole .
    ?adviseeRole core:relatedBy ?advisingRelationship .
    ?advisee rdfs:label ?label .
    ?advisee core:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval core:end ?date .
    ?date core:dateTime ?dateTime .
}
