PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?patent rdfs:label ?nameWithId .
} WHERE {
    <[(${uri})]> vivo:assigneeFor ?patent .
    ?patent rdfs:label ?name .
    BIND( CONCAT( STR(?name), REPLACE(STR(?patent), "(^.*/)", "::") ) AS ?nameWithId ) .
}