PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
 
CONSTRUCT {
    ?patent vitro:mostSpecificType ?type .
} WHERE {
    <[(${uri})]> vivo:assigneeFor ?patent .
    ?patent vitro:mostSpecificType ?type .
}