PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?date vivo:dateTime ?dateTimeWithId .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?awardReceipt .
    ?awardReceipt a vivo:AwardReceipt .
    ?awardReceipt vivo:dateTimeValue ?date .
    ?date vivo:dateTime ?dateTime .
    BIND( CONCAT( STR(?dateTime), REPLACE(STR(?awardReceipt), "(^.*/)", "::") ) AS ?dateTimeWithId ) .
}