PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
 
CONSTRUCT {
    ?cos vitro:mostSpecificType ?type .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?role .
    ?role a vivo:EditorRole .
    ?role vivo:roleContributesTo ?cos .
    ?cos vitro:mostSpecificType ?type .
}