PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?eligibleFor rdfs:label ?name .
} WHERE {
    <[(${uri})]> vivo:eligibleFor ?eligibleFor .
    ?eligibleFor rdfs:label ?name .
}