PREFIX vivo: <http://vivoweb.org/ontology/core#>
 
CONSTRUCT {
    ?dateIssued vivo:dateTime ?dateTimeWithId .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?issuedCredential .
    ?issuedCredential a vivo:IssuedCredential .
    ?credentials vivo:dateIssued ?dateIssued .
    ?dateIssued vivo:dateTime ?dateTime .
    BIND( CONCAT( STR(?dateTime), REPLACE(STR(?credentials), "(^.*/)", "::") ) AS ?dateTimeWithId ) .
}