PREFIX vivo: <http://vivoweb.org/ontology/core#>
 
CONSTRUCT {
    ?dateIssued vivo:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?issuedCredential .
    ?issuedCredential a vivo:IssuedCredential .
    ?credentials vivo:dateIssued ?dateIssued .
    ?dateIssued vivo:dateTime ?dateTime .
}