PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?eligibleFor rdfs:label ?nameWithId .
} WHERE {
    <[(${uri})]> vivo:eligibleFor ?eligibleFor .
    ?eligibleFor rdfs:label ?name .
    BIND( CONCAT( STR(?name), REPLACE(STR(?eligibleFor), "(^.*/)", "::") ) AS ?nameWithId ) .
}