PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?eligibleFor rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> vivo:eligibleFor ?eligibleFor .
    ?eligibleFor rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?eligibleFor), "(^.*/)", "::") ) AS ?labelWithId ) .
}