PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
 
CONSTRUCT {
    ?eligibleFor vitro:mostSpecificType ?type .
} WHERE {
    <[(${uri})]> vivo:eligibleFor ?eligibleFor .
    ?eligibleFor vitro:mostSpecificType ?type .
}