PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?educationalTraining ?educationalTrainingProperty ?educationalTrainingObject .
    ?educationalTraining ?awardedDegreeProperty ?awardedDegreeObject .
    ?educationalTraining ?dateProperty ?dateObject .
} WHERE {
    <[(${uri})]> obo:RO_0000056 ?educationalTraining .
    ?educationalTraining a core:EducationalProcess .
    ?educationalTraining ?educationalTrainingProperty ?educationalTrainingObject .
    ?educationalTraining obo:RO_0002234 ?awardedDegree .
    ?awardedDegree a core:AwardedDegree .
    ?awardedDegree ?awardedDegreeProperty ?awardedDegreeObject .
    ?educationalTraining core:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval core:end ?date .
    ?date ?dateProperty ?dateObject .
}
