PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>

CONSTRUCT {
    ?document tamu:fullAuthorList ?fullAuthorList .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?editor .
    ?editor a vivo:Editorship .
    ?editor vivo:relates ?document .
    ?document a bibo:Document .
    ?document tamu:fullAuthorList ?fullAuthorList .
}