PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?date vivo:dateTime ?dateTimeWithId .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?editor .
    ?editor a vivo:Editorship .
    ?editor vivo:relates ?document .
    ?document a bibo:Document .
    ?document ?dateTimeValue ?date .
    ?date vivo:dateTime ?dateTime .
    BIND( CONCAT( STR(?dateTime), REPLACE(STR(?document), "(^.*/)", "::") ) AS ?dateTimeWithId ) .
}