PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX bibo: <http://purl.org/ontology/bibo/>

CONSTRUCT {
    ?document bibo:pageEnd ?pageEnd
} WHERE {
    <[(${uri})]> vivo:relatedBy ?editor .
    ?editor a vivo:Editorship .
    ?editor vivo:relates ?document .
    ?document a bibo:Document .
    ?document bibo:pageEnd ?pageEnd
}