PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?document vitro:mostSpecificType ?mostSpecificTypeWithId .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?editor .
    ?editor a vivo:Editorship .
    ?editor vivo:relates ?document .
    ?document a bibo:Document .
    ?document vitro:mostSpecificType ?mostSpecificType .
    BIND( CONCAT( STR(?mostSpecificType), REPLACE(STR(?document), "(^.*/)", "::") ) AS ?mostSpecificTypeWithId ) .
}