PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?role rdfs:label ?label .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?role .
    ?role a vivo:TeacherRole .
    ?role rdfs:label ?label .
}