PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
 
CONSTRUCT {
    ?training vitro:mostSpecificType ?type .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?teacherRole .
    ?teacherRole a core:TeacherRole .
    ?teacherRole obo:BFO_0000054  ?training .
    ?training vitro:mostSpecificType ?type .
}