PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?work rdfs:label ?titleWithId .
} WHERE {
    <[(${uri})]> tamu:ETDChairOf ?work .
    ?work rdfs:label ?title .
    BIND( CONCAT( STR(?title), REPLACE(STR(?work), "(^.*/)", "::") ) AS ?titleWithId ) .
}