PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
    ?hasTelephone vcard:telephone ?fax .
} WHERE {
    <[(${uri})]> obo:ARG_2000028 ?vcard .
    ?vcard vcard:hasTelephone ?hasTelephone .
    ?hasTelephone a vcard:Fax .
    ?hasTelephone vcard:telephone ?fax .
}