PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
 
CONSTRUCT {
    ?document vitro:mostSpecificType ?type .
} WHERE {
    <[(${uri})]> vivo:featuredIn ?document .
    ?document vitro:mostSpecificType ?type .
    ?document vitro:mostSpecificType ?type .
    FILTER (contains(str(?type), "http://purl.org/ontology/bibo/"))
}