PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?technique rdfs:label ?type .
} WHERE {
    <[(${uri})]> obo:ERO_0000033 ?technique .
    ?technique rdfs:label ?name .
    BIND( CONCAT( STR(?name), REPLACE(STR(?technique), "(^.*/)", "::") ) AS ?nameWithId ) .
}