PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?grant rdfs:label ?nameWithId .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?role .
    ?role a vivo:InvestigatorRole .
    ?role vivo:relatedBy ?grant .
    ?grant rdfs:label ?name .
    BIND( CONCAT( STR(?name), REPLACE(STR(?grant), "(^.*/)", "::") ) AS ?nameWithId ) .
}