PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?membership rdfs:label ?label .
    ?membership core:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?memberRole .
    ?memberRole a core:MemberRole .
    ?memberRole core:roleContributesTo ?membership .
    ?membership rdfs:label ?label .
    ?membership core:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval core:end ?date .
    ?date core:dateTime ?dateTime .
}
