PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?organization vitro:mostSpecificType ?typeWithIds .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?role .
    ?role a vivo:MemberRole .
    ?role vivo:roleContributesTo ?organization .
    ?organization vitro:mostSpecificType ?type .
    BIND( CONCAT( STR(?type), REPLACE(STR(?role), "(^.*/)", "::"), REPLACE(STR(?organization), "(^.*/)", "::") ) AS ?typeWithIds ) .
}