PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?research rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?role .
    ?role a vivo:ResearcherRole .
    ?role vitro:mostSpecificType ?mostSpecificType .
    {
        ?role vivo:relatedBy ?research .
    } UNION {
        ?role obo:BFO_0000054 ?research .
    }
    ?research rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?research), "(^.*/)", "::") ) AS ?labelWithId ) .
    FILTER(?mostSpecificType = vivo:ResearcherRole)
}