PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
 
CONSTRUCT {
    ?technique vitro:mostSpecificType ?mostSpecificTypeWithId .
} WHERE {
    <[(${uri})]> obo:ERO_0000397 ?technique .
    ?technique vitro:mostSpecificType ?mostSpecificType .
    BIND( CONCAT( STR(?mostSpecificType), REPLACE(STR(?technique), "(^.*/)", "::") ) AS ?mostSpecificTypeWithId ) .
}