PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>

CONSTRUCT {
    <[(${uri})]> ?property ?object .
} WHERE {
    <[(${uri})]> ?property ?object .
    FILTER (?property != core:hasResearchArea)
    FILTER (?property != core:relatedBy)
    FILTER (?property != core:relates)
    FILTER (?property != obo:ARG_2000028)
    FILTER (?property != obo:BFO_0000054)
    FILTER (?property != obo:RO_0000053)
    FILTER (?property != obo:RO_0000056)
    FILTER (?property != obo:RO_0002234)
    FILTER (?property != rdf:type)
    FILTER (?property != tamu:ETDChairOf)
    FILTER (?property != vitro:mostSpecificType)
    FILTER (?property != vitro-public:mainImage)
}
