PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?position rdfs:label ?label .
} WHERE {
    <[(${uri})]> core:relatedBy ?position .
    ?position a core:Position .
    ?position rdfs:label ?label .
}
