PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?position rdfs:label ?nameWithId .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?position .
    ?position a vivo:Position .
    ?position rdfs:label ?name .
    BIND( CONCAT( STR(?name), REPLACE(STR(?position), "(^.*/)", "::") ) AS ?nameWithId ) .
}