PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://purl.org/NET/c4dm/event.owl#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>

CONSTRUCT {
    ?event rdfs:label ?name .
} WHERE {
    <[(${uri})]> obo:RO_0000053 ?role .
    ?role a vivo:PresenterRole .
    ?role obo:BFO_0000054 ?presentation .
    ?presentation obo:BFO_0000050 ?event .
    ?event a owl:Event .
    ?event rdfs:label ?name .
    ?event vitro:mostSpecificType ?type .
    FILTER (contains(str(?type), "http://purl.org/ontology/bibo/"))
}