PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
 
CONSTRUCT {
    ?publication rdfs:label ?label .
    ?publication vitro:mostSpecificType ?type .
    ?publication core:dateTime ?dateTime .
} WHERE {
    <[(${uri})]> core:relatedBy ?authorship .
    ?authorship a core:Authorship .
    ?authorship core:relates ?publication .
    ?publication a obo:IAO_0000030 .
    ?publication rdfs:label ?label .
    ?publication vitro:mostSpecificType ?type .
    ?publication ?dateTimeValue ?date .
    ?date core:dateTime ?dateTime .
    FILTER (contains(str(?type), "http://purl.org/ontology/bibo/"))
}
