PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
CONSTRUCT {
    ?publicationVenue rdfs:label ?labelWithId .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?authorship .
    ?authorship a vivo:Authorship .
    ?authorship vivo:relates ?publication .
    ?publication a obo:IAO_0000030 .
    ?publication vivo:hasPublicationVenue ?publicationVenue .
    ?publicationVenue rdfs:label ?label .
    BIND( CONCAT( STR(?label), REPLACE(STR(?publication), "(^.*/)", "::") ) AS ?labelWithId ) .
}