PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
 
CONSTRUCT {
    ?publication tamu:bookTitleForChapter ?bookTitleForChapterWithId .
} WHERE {
    <[(${uri})]> vivo:relatedBy ?authorship .
    ?authorship a vivo:Authorship .
    ?authorship vivo:relates ?publication .
    ?publication a obo:IAO_0000030 .
    ?publication tamu:bookTitleForChapter ?bookTitleForChapter .
    BIND( CONCAT( STR(?bookTitleForChapter), REPLACE(STR(?publication), "(^.*/)", "::") ) AS ?bookTitleForChapterWithId ) .
}