PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
    ?hasAddress vcard:streetAddress ?streetAddress .
} WHERE {
    <[(${uri})]> obo:ARG_2000028 ?vcard .
    ?vcard vcard:hasAddress ?hasAddress .
    ?hasAddress vcard:streetAddress ?streetAddress .
}